enable_notifications: true
notify_by_default: true
notify_when_using: 'no'
number_of_seconds_considered_away: 120
hide_form_filter_tips: false
hide_recipient_field_when_prefilled: false
_core:
  default_config_hash: MbeU9ZYX8x1qoHsBz3PJOy-PoR7HkHwzOKY0sbgmGdo
create_message_label: 'Create Private Message'
