<?php

/**
 * @file
 * Grab user info for certificate display.
 */

/**
 * Load user information and make it available to opigno_certificate.
 */
function cme_preprocess_opigno_certificate(&$variables) {
  $user = load(\Drupal::currentUser()->id());
  $variables['firstname'] = $user->get('field_first_name')->value;
  $variables['lastname'] = $user->get('field_last_name')->value;
  $variables['profession'] = $user->get('field_profession_taxonomy_ref')->entity->label();
}
